spring.application.name=weather-api
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

weather.api.key=${WEATHER_API_KEY}
weather.api.url=https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/
weather.cache.ttl=3600
weather.rate.limit=100

server.port=8000
logging.level.org.springframework=DEBUG
logging.level.com.example.weatherapi.cache=DEBUG